language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install python-coveralls
before_script:
  - pip install python-coveralls
  - pip install coveralls
  - pip install coverage
script:
  - nosetests --with-coverage
  #- coverage run test.py
after_success:
  - coveralls